# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ideas4all_city_simulator_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1482, 936)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_mainframe = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.widget_mainframe.sizePolicy().hasHeightForWidth())
        self.widget_mainframe.setSizePolicy(sizePolicy)
        self.widget_mainframe.setObjectName("widget_mainframe")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_mainframe)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.preeq_post_tabwidget = QtWidgets.QTabWidget(self.widget_mainframe)
        self.preeq_post_tabwidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.preeq_post_tabwidget.setObjectName("preeq_post_tabwidget")
        self.pretab = QtWidgets.QWidget()
        self.pretab.setObjectName("pretab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pretab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.pretab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.treeWidget)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.configure_simulation_pushbutton = QtWidgets.QPushButton(self.groupBox)
        self.configure_simulation_pushbutton.setEnabled(False)
        self.configure_simulation_pushbutton.setObjectName("configure_simulation_pushbutton")
        self.verticalLayout_6.addWidget(self.configure_simulation_pushbutton)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.pretab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget_vtk = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.tabWidget_vtk.sizePolicy().hasHeightForWidth())
        self.tabWidget_vtk.setSizePolicy(sizePolicy)
        self.tabWidget_vtk.setObjectName("tabWidget_vtk")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabWidget_vtk)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_vtk = QtWidgets.QGroupBox(self.tabWidget_vtk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.groupBox_vtk.sizePolicy().hasHeightForWidth())
        self.groupBox_vtk.setSizePolicy(sizePolicy)
        self.groupBox_vtk.setObjectName("groupBox_vtk")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_vtk)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vtkLayout = QtWidgets.QVBoxLayout()
        self.vtkLayout.setObjectName("vtkLayout")
        self.verticalLayout_5.addLayout(self.vtkLayout)
        self.verticalLayout_3.addWidget(self.groupBox_vtk)
        self.groupBox_vtkTaskbar = QtWidgets.QGroupBox(self.tabWidget_vtk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_vtkTaskbar.sizePolicy().hasHeightForWidth())
        self.groupBox_vtkTaskbar.setSizePolicy(sizePolicy)
        self.groupBox_vtkTaskbar.setObjectName("groupBox_vtkTaskbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_vtkTaskbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_vtkTaskbar)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EnableSelection_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.EnableSelection_checkBox.setObjectName("EnableSelection_checkBox")
        self.verticalLayout_2.addWidget(self.EnableSelection_checkBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buildings_pushbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.buildings_pushbutton.setEnabled(False)
        self.buildings_pushbutton.setCheckable(True)
        self.buildings_pushbutton.setObjectName("buildings_pushbutton")
        self.horizontalLayout_5.addWidget(self.buildings_pushbutton)
        self.buildingBlocks_pushbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.buildingBlocks_pushbutton.setEnabled(False)
        self.buildingBlocks_pushbutton.setCheckable(True)
        self.buildingBlocks_pushbutton.setObjectName("buildingBlocks_pushbutton")
        self.horizontalLayout_5.addWidget(self.buildingBlocks_pushbutton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.append_pushbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.append_pushbutton.setEnabled(False)
        self.append_pushbutton.setDefault(False)
        self.append_pushbutton.setFlat(False)
        self.append_pushbutton.setObjectName("append_pushbutton")
        self.verticalLayout_2.addWidget(self.append_pushbutton)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_vtkTaskbar)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.showonly_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.showonly_pushButton.setEnabled(False)
        self.showonly_pushButton.setObjectName("showonly_pushButton")
        self.horizontalLayout_3.addWidget(self.showonly_pushButton)
        self.invert_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.invert_pushButton.setEnabled(False)
        self.invert_pushButton.setObjectName("invert_pushButton")
        self.horizontalLayout_3.addWidget(self.invert_pushButton)
        self.showall_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.showall_pushButton.setEnabled(False)
        self.showall_pushButton.setObjectName("showall_pushButton")
        self.horizontalLayout_3.addWidget(self.showall_pushButton)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_3.addWidget(self.groupBox_vtkTaskbar)
        self.tabWidget.addTab(self.tabWidget_vtk, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.preeq_post_tabwidget.addTab(self.pretab, "")
        self.posttab = QtWidgets.QWidget()
        self.posttab.setObjectName("posttab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.posttab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.posttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.param_tabWidget = QtWidgets.QTabWidget(self.groupBox_4)
        self.param_tabWidget.setEnabled(True)
        self.param_tabWidget.setObjectName("param_tabWidget")
        self.simulation_tab = QtWidgets.QWidget()
        self.simulation_tab.setObjectName("simulation_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.simulation_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.simulation_tab)
        self.groupBox_11.setEnabled(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.runorloadcheckBox = QtWidgets.QCheckBox(self.groupBox_11)
        self.runorloadcheckBox.setEnabled(True)
        self.runorloadcheckBox.setChecked(False)
        self.runorloadcheckBox.setObjectName("runorloadcheckBox")
        self.verticalLayout_14.addWidget(self.runorloadcheckBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_dt = QtWidgets.QLabel(self.groupBox_7)
        self.label_dt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_dt.setObjectName("label_dt")
        self.gridLayout.addWidget(self.label_dt, 3, 0, 1, 1)
        self.simtype_comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.simtype_comboBox.setObjectName("simtype_comboBox")
        self.simtype_comboBox.addItem("")
        self.simtype_comboBox.addItem("")
        self.gridLayout.addWidget(self.simtype_comboBox, 1, 1, 1, 1)
        self.mode_spinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.mode_spinBox.setProperty("value", 3)
        self.mode_spinBox.setObjectName("mode_spinBox")
        self.gridLayout.addWidget(self.mode_spinBox, 4, 1, 1, 1)
        self.duration_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.duration_doubleSpinBox.setProperty("value", 10.0)
        self.duration_doubleSpinBox.setObjectName("duration_doubleSpinBox")
        self.gridLayout.addWidget(self.duration_doubleSpinBox, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.dt_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.dt_doubleSpinBox.setMaximum(1.0)
        self.dt_doubleSpinBox.setSingleStep(0.01)
        self.dt_doubleSpinBox.setProperty("value", 0.01)
        self.dt_doubleSpinBox.setObjectName("dt_doubleSpinBox")
        self.gridLayout.addWidget(self.dt_doubleSpinBox, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.unit_comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.unit_comboBox.setObjectName("unit_comboBox")
        self.unit_comboBox.addItem("")
        self.unit_comboBox.addItem("")
        self.gridLayout.addWidget(self.unit_comboBox, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_8)
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.rc_checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.rc_checkBox.setChecked(True)
        self.rc_checkBox.setObjectName("rc_checkBox")
        self.gridLayout_3.addWidget(self.rc_checkBox, 0, 1, 1, 1)
        self.ws_checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.ws_checkBox.setObjectName("ws_checkBox")
        self.gridLayout_3.addWidget(self.ws_checkBox, 1, 1, 1, 1)
        self.cw_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.cw_doubleSpinBox.setMinimum(10.0)
        self.cw_doubleSpinBox.setMaximum(30.0)
        self.cw_doubleSpinBox.setProperty("value", 18.0)
        self.cw_doubleSpinBox.setObjectName("cw_doubleSpinBox")
        self.gridLayout_3.addWidget(self.cw_doubleSpinBox, 2, 1, 1, 1)
        self.bd_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.bd_doubleSpinBox.setMinimum(10.0)
        self.bd_doubleSpinBox.setMaximum(30.0)
        self.bd_doubleSpinBox.setProperty("value", 24.0)
        self.bd_doubleSpinBox.setObjectName("bd_doubleSpinBox")
        self.gridLayout_3.addWidget(self.bd_doubleSpinBox, 3, 1, 1, 1)
        self.bw_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.bw_doubleSpinBox.setMinimum(10.0)
        self.bw_doubleSpinBox.setMaximum(30.0)
        self.bw_doubleSpinBox.setProperty("value", 18.0)
        self.bw_doubleSpinBox.setObjectName("bw_doubleSpinBox")
        self.gridLayout_3.addWidget(self.bw_doubleSpinBox, 4, 1, 1, 1)
        self.gd_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.gd_doubleSpinBox.setMinimum(10.0)
        self.gd_doubleSpinBox.setMaximum(30.0)
        self.gd_doubleSpinBox.setProperty("value", 24.0)
        self.gd_doubleSpinBox.setObjectName("gd_doubleSpinBox")
        self.gridLayout_3.addWidget(self.gd_doubleSpinBox, 5, 1, 1, 1)
        self.gw_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.gw_doubleSpinBox.setMinimum(10.0)
        self.gw_doubleSpinBox.setMaximum(30.0)
        self.gw_doubleSpinBox.setProperty("value", 18.0)
        self.gw_doubleSpinBox.setObjectName("gw_doubleSpinBox")
        self.gridLayout_3.addWidget(self.gw_doubleSpinBox, 6, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.acc_checkbutton = QtWidgets.QCheckBox(self.groupBox_9)
        self.acc_checkbutton.setChecked(True)
        self.acc_checkbutton.setObjectName("acc_checkbutton")
        self.verticalLayout_9.addWidget(self.acc_checkbutton)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lon_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.lon_pushButton.setObjectName("lon_pushButton")
        self.gridLayout_5.addWidget(self.lon_pushButton, 1, 0, 1, 1)
        self.lat_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.lat_pushButton.setObjectName("lat_pushButton")
        self.gridLayout_5.addWidget(self.lat_pushButton, 0, 0, 1, 1)
        self.latfile_label = QtWidgets.QLabel(self.groupBox_9)
        self.latfile_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.latfile_label.setObjectName("latfile_label")
        self.gridLayout_5.addWidget(self.latfile_label, 0, 1, 1, 1)
        self.lonfile_label = QtWidgets.QLabel(self.groupBox_9)
        self.lonfile_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lonfile_label.setObjectName("lonfile_label")
        self.gridLayout_5.addWidget(self.lonfile_label, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_5)
        self.loadsscenario_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.loadsscenario_pushButton.setEnabled(False)
        self.loadsscenario_pushButton.setObjectName("loadsscenario_pushButton")
        self.verticalLayout_9.addWidget(self.loadsscenario_pushButton)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_liveloads = QtWidgets.QLabel(self.groupBox_9)
        self.label_liveloads.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_liveloads.setObjectName("label_liveloads")
        self.horizontalLayout_17.addWidget(self.label_liveloads)
        self.ll_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.ll_doubleSpinBox.setProperty("value", 40.0)
        self.ll_doubleSpinBox.setObjectName("ll_doubleSpinBox")
        self.horizontalLayout_17.addWidget(self.ll_doubleSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.verticalLayout_14.addWidget(self.groupBox_9)
        self.verticalLayout_10.addWidget(self.groupBox_11)
        self.groupBox_10 = QtWidgets.QGroupBox(self.simulation_tab)
        self.groupBox_10.setEnabled(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.runsimulation_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.runsimulation_pushButton.setEnabled(False)
        self.runsimulation_pushButton.setObjectName("runsimulation_pushButton")
        self.horizontalLayout_16.addWidget(self.runsimulation_pushButton)
        self.runfilename_label = QtWidgets.QLabel(self.groupBox_10)
        self.runfilename_label.setEnabled(False)
        self.runfilename_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runfilename_label.setObjectName("runfilename_label")
        self.horizontalLayout_16.addWidget(self.runfilename_label)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.run_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.run_pushButton.setEnabled(False)
        self.run_pushButton.setObjectName("run_pushButton")
        self.verticalLayout_11.addWidget(self.run_pushButton)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.loadsimulation_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.loadsimulation_pushButton.setEnabled(True)
        self.loadsimulation_pushButton.setObjectName("loadsimulation_pushButton")
        self.horizontalLayout_15.addWidget(self.loadsimulation_pushButton)
        self.loadfilename_label = QtWidgets.QLabel(self.groupBox_10)
        self.loadfilename_label.setEnabled(True)
        self.loadfilename_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadfilename_label.setObjectName("loadfilename_label")
        self.horizontalLayout_15.addWidget(self.loadfilename_label)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.showresults_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.showresults_pushButton.setEnabled(False)
        self.showresults_pushButton.setFlat(False)
        self.showresults_pushButton.setObjectName("showresults_pushButton")
        self.verticalLayout_11.addWidget(self.showresults_pushButton)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addWidget(self.groupBox_10)
        self.param_tabWidget.addTab(self.simulation_tab, "")
        self.postprocessing_tab = QtWidgets.QWidget()
        self.postprocessing_tab.setObjectName("postprocessing_tab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.postprocessing_tab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.animate_groupBox = QtWidgets.QGroupBox(self.postprocessing_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.animate_groupBox.sizePolicy().hasHeightForWidth())
        self.animate_groupBox.setSizePolicy(sizePolicy)
        self.animate_groupBox.setObjectName("animate_groupBox")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.animate_groupBox)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Start_Animation_Push_Button = QtWidgets.QPushButton(self.animate_groupBox)
        self.Start_Animation_Push_Button.setEnabled(False)
        self.Start_Animation_Push_Button.setCheckable(True)
        self.Start_Animation_Push_Button.setObjectName("Start_Animation_Push_Button")
        self.verticalLayout_8.addWidget(self.Start_Animation_Push_Button)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.animate_groupBox)
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.scalefact_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.animate_groupBox)
        self.scalefact_doubleSpinBox.setProperty("value", 1.0)
        self.scalefact_doubleSpinBox.setObjectName("scalefact_doubleSpinBox")
        self.horizontalLayout_14.addWidget(self.scalefact_doubleSpinBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.time_label = QtWidgets.QLabel(self.animate_groupBox)
        self.time_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_8.addWidget(self.time_label)
        self.dial = QtWidgets.QDial(self.animate_groupBox)
        self.dial.setEnabled(True)
        self.dial.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dial.setAutoFillBackground(False)
        self.dial.setMinimum(-2)
        self.dial.setSingleStep(3)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(True)
        self.dial.setNotchTarget(1.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.verticalLayout_8.addWidget(self.dial)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.verticalLayout_15.addWidget(self.animate_groupBox)
        self.groupBox_12 = QtWidgets.QGroupBox(self.postprocessing_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.groupBox_13)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.tensorresult_comboBox = QtWidgets.QComboBox(self.groupBox_13)
        self.tensorresult_comboBox.setObjectName("tensorresult_comboBox")
        self.verticalLayout_17.addWidget(self.tensorresult_comboBox)
        self.label_15 = QtWidgets.QLabel(self.groupBox_13)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15)
        self.scalarresult_comboBox = QtWidgets.QComboBox(self.groupBox_13)
        self.scalarresult_comboBox.setObjectName("scalarresult_comboBox")
        self.verticalLayout_17.addWidget(self.scalarresult_comboBox)
        self.verticalLayout_13.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.legend_layout = QtWidgets.QVBoxLayout()
        self.legend_layout.setObjectName("legend_layout")
        self.verticalLayout_18.addLayout(self.legend_layout)
        self.verticalLayout_13.addWidget(self.groupBox_14)
        self.verticalLayout_15.addWidget(self.groupBox_12)
        self.param_tabWidget.addTab(self.postprocessing_tab, "")
        self.horizontalLayout_6.addWidget(self.param_tabWidget)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.Postprocessing_tabwidget = QtWidgets.QTabWidget(self.posttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Postprocessing_tabwidget.sizePolicy().hasHeightForWidth())
        self.Postprocessing_tabwidget.setSizePolicy(sizePolicy)
        self.Postprocessing_tabwidget.setTabsClosable(True)
        self.Postprocessing_tabwidget.setMovable(True)
        self.Postprocessing_tabwidget.setObjectName("Postprocessing_tabwidget")
        self.tab_seismic_origins = QtWidgets.QWidget()
        self.tab_seismic_origins.setObjectName("tab_seismic_origins")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_seismic_origins)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_seismic_origins)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.Postprocessing_tabwidget.addTab(self.tab_seismic_origins, "")
        self.tab_postcity = QtWidgets.QWidget()
        self.tab_postcity.setObjectName("tab_postcity")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_postcity)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_postcity)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.vtkPostLayout = QtWidgets.QHBoxLayout()
        self.vtkPostLayout.setObjectName("vtkPostLayout")
        self.horizontalLayout_11.addLayout(self.vtkPostLayout)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.Postprocessing_tabwidget.addTab(self.tab_postcity, "")
        self.horizontalLayout_9.addWidget(self.Postprocessing_tabwidget)
        self.preeq_post_tabwidget.addTab(self.posttab, "")
        self.horizontalLayout_8.addWidget(self.preeq_post_tabwidget)
        self.gridLayout_7.addWidget(self.widget_mainframe, 0, 0, 1, 1)
        self.groupBox_Log = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_Log.sizePolicy().hasHeightForWidth())
        self.groupBox_Log.setSizePolicy(sizePolicy)
        self.groupBox_Log.setToolTipDuration(-3)
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Log)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit_Log = QtWidgets.QTextEdit(self.groupBox_Log)
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.verticalLayout_4.addWidget(self.textEdit_Log)
        self.gridLayout_7.addWidget(self.groupBox_Log, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1482, 21))
        self.menubar.setObjectName("menubar")
        self.menusome = QtWidgets.QMenu(self.menubar)
        self.menusome.setObjectName("menusome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menusome.addAction(self.actionopen)
        self.menubar.addAction(self.menusome.menuAction())

        self.retranslateUi(MainWindow)
        self.preeq_post_tabwidget.setCurrentIndex(1)
        self.param_tabWidget.setCurrentIndex(0)
        self.Postprocessing_tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ideas4All - EartQuaqeSimulator"))
        self.groupBox.setTitle(_translate("MainWindow", "Navigation"))
        self.label_2.setText(_translate("MainWindow", "All Entitites"))
        self.label.setText(_translate("MainWindow", "Simulation Pool Selected Entities"))
        self.configure_simulation_pushbutton.setText(_translate("MainWindow", "Configure Simulation"))
        self.groupBox_vtk.setTitle(_translate("MainWindow", "PreRenderWindow"))
        self.groupBox_vtkTaskbar.setTitle(_translate("MainWindow", "RenderWindow Taskbar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Selection"))
        self.EnableSelection_checkBox.setText(_translate("MainWindow", "Enable Selection"))
        self.buildings_pushbutton.setText(_translate("MainWindow", "Buildings"))
        self.buildingBlocks_pushbutton.setText(_translate("MainWindow", "Building Blocks"))
        self.append_pushbutton.setText(_translate("MainWindow", "<----x  Append to the Simulation Pool"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Visibility"))
        self.showonly_pushButton.setText(_translate("MainWindow", "showonly"))
        self.invert_pushButton.setText(_translate("MainWindow", "invert"))
        self.showall_pushButton.setText(_translate("MainWindow", "showall"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidget_vtk), _translate("MainWindow", "Pre-City"))
        self.preeq_post_tabwidget.setTabText(self.preeq_post_tabwidget.indexOf(self.pretab), _translate("MainWindow", "Pre-EQ"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Parameters"))
        self.groupBox_11.setTitle(_translate("MainWindow", "RunParams"))
        self.runorloadcheckBox.setText(_translate("MainWindow", "Set Parameter for Run"))
        self.groupBox_7.setTitle(_translate("MainWindow", "SolverParams"))
        self.label_dt.setText(_translate("MainWindow", "Time Step [s]"))
        self.simtype_comboBox.setCurrentText(_translate("MainWindow", "Dynamic"))
        self.simtype_comboBox.setItemText(0, _translate("MainWindow", "Dynamic"))
        self.simtype_comboBox.setItemText(1, _translate("MainWindow", "Static Pushover"))
        self.label_5.setText(_translate("MainWindow", "# of Modes [-]"))
        self.label_3.setText(_translate("MainWindow", "Sim. Type"))
        self.label_4.setText(_translate("MainWindow", "Duration [s]"))
        self.label_16.setText(_translate("MainWindow", "Unit System"))
        self.unit_comboBox.setCurrentText(_translate("MainWindow", "US"))
        self.unit_comboBox.setItemText(0, _translate("MainWindow", "US"))
        self.unit_comboBox.setItemText(1, _translate("MainWindow", "SI"))
        self.groupBox_8.setTitle(_translate("MainWindow", "TopoParams"))
        self.label_7.setText(_translate("MainWindow", "W Section"))
        self.label_10.setText(_translate("MainWindow", "Girder Width [inch]"))
        self.label_9.setText(_translate("MainWindow", "Beam Depth [inch]"))
        self.label_11.setText(_translate("MainWindow", "Beam Width [inch]"))
        self.label_8.setText(_translate("MainWindow", "Column Width/Depth [inch]"))
        self.label_12.setText(_translate("MainWindow", "Girder Depth [inch]"))
        self.label_6.setText(_translate("MainWindow", "RC Section"))
        self.rc_checkBox.setText(_translate("MainWindow", "True"))
        self.ws_checkBox.setText(_translate("MainWindow", "True"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Excitation"))
        self.acc_checkbutton.setText(_translate("MainWindow", "Apply Uniform Acceleration"))
        self.lon_pushButton.setText(_translate("MainWindow", "LoadLonAccFile"))
        self.lat_pushButton.setText(_translate("MainWindow", "LoadLatAccFile"))
        self.latfile_label.setText(_translate("MainWindow", "*at2"))
        self.lonfile_label.setText(_translate("MainWindow", "*at2"))
        self.loadsscenario_pushButton.setText(_translate("MainWindow", "LoadScenarioFromMap"))
        self.label_liveloads.setText(_translate("MainWindow", "Live Loads [psf]"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Simulation"))
        self.runsimulation_pushButton.setText(_translate("MainWindow", "RunSimulation to:"))
        self.runfilename_label.setText(_translate("MainWindow", "TextLabel"))
        self.run_pushButton.setText(_translate("MainWindow", "RUN"))
        self.loadsimulation_pushButton.setText(_translate("MainWindow", " LoadSimulation from:"))
        self.loadfilename_label.setText(_translate("MainWindow", "TextLabel"))
        self.showresults_pushButton.setText(_translate("MainWindow", "ShowResults"))
        self.param_tabWidget.setTabText(self.param_tabWidget.indexOf(self.simulation_tab), _translate("MainWindow", "SimParam"))
        self.animate_groupBox.setTitle(_translate("MainWindow", "AnimationGroup"))
        self.Start_Animation_Push_Button.setText(_translate("MainWindow", "StartAnimation"))
        self.label_13.setText(_translate("MainWindow", "Scale Factor [-]"))
        self.time_label.setText(_translate("MainWindow", "Time: 0.0 sc."))
        self.groupBox_12.setTitle(_translate("MainWindow", "ColorPlotGroup"))
        self.label_14.setText(_translate("MainWindow", "TensorName"))
        self.label_15.setText(_translate("MainWindow", "ScalarOrInvariantOfTensor"))
        self.groupBox_14.setTitle(_translate("MainWindow", "LegendView"))
        self.param_tabWidget.setTabText(self.param_tabWidget.indexOf(self.postprocessing_tab), _translate("MainWindow", "PostParam"))
        self.groupBox_5.setTitle(_translate("MainWindow", "MapWindow"))
        self.Postprocessing_tabwidget.setTabText(self.Postprocessing_tabwidget.indexOf(self.tab_seismic_origins), _translate("MainWindow", "Seismic Origins"))
        self.groupBox_6.setTitle(_translate("MainWindow", "PostRenderWindow"))
        self.Postprocessing_tabwidget.setTabText(self.Postprocessing_tabwidget.indexOf(self.tab_postcity), _translate("MainWindow", "Post-City"))
        self.preeq_post_tabwidget.setTabText(self.preeq_post_tabwidget.indexOf(self.posttab), _translate("MainWindow", "Post-EQ"))
        self.groupBox_Log.setTitle(_translate("MainWindow", "LogWindow"))
        self.menusome.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "open"))
